image: texlive

before_script:
    - bash .ci/install.sh

make:
    stage: build
    script:
        - make

testrefs:
    stage: test
    script:
        - make testrefs

testbib:
    stage: test
    script:
        - make testbib

testcountbib:
    stage: test
    script:
        - make testcountbib

testfonts:
    stage: test
    script:
        - make testfonts

testpdfversion:
    stage: test
    script:
        - make testpdfversion

testcountpages:
    stage: test
    script:
        - make testcountpages
