# Temporary files
TEMP=*.bbl *.blg *.synctex.gz *.aux *.toc *.ptc *.out *.ist *.ac? *.alg *.tdo *.lo? *.gl? *.snm *.nav
# Avoid removing temp files
.INTERMEDIATE: $(TEMP)

# Commands + arguments
TEX = lualatex -interaction=nonstopmode -synctex=1
BIB = bibtex
GLOSSARY = makeglossaries
